hl.on("hyprland.start", function()
	hl.exec_cmd("hyprlock")
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaybg -i " .. os.getenv("HOME") .. "/Pictures/Wallpapers/wallpaper.jpg -m fill")
	hl.exec_cmd("systemctl --user start hyprpolkitagent")
	hl.exec_cmd("wl-clip-persist --clipboard both")
	hl.exec_cmd("clipse -listen")
	hl.exec_cmd("udiskie")
end)

-- Restart waybar on reload (picks up config changes)
hl.exec_cmd("pkill waybar; waybar")
