# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[directory]
truncation_length = 3

[cmd_duration]
min_time = 2
format   = 'took [$duration]($style)'
style    = "bold red"

[jobs]
threshold = 1
